DROP TABLE IF EXISTS PATIENTS;
DROP TABLE IF EXISTS CHIROPRACTICEXPERIENCES;
DROP TABLE IF EXISTS PATIENT_CHIROPRACTICEXPERIENCES;
DROP TABLE IF EXISTS FAMILYHISTORIES;
DROP TABLE IF EXISTS PATIENT_FAMILYHISTORIES;
DROP TABLE IF EXISTS MEDICALHISTORIES;
DROP TABLE IF EXISTS PATIENT_MEDICALHISTORIES;
DROP TABLE IF EXISTS HEALTHHABITS;
DROP TABLE IF EXISTS PATIENT_HEALTHHABITS;
DROP TABLE IF EXISTS CHILDHOODTRUAMAS;
DROP TABLE IF EXISTS PATIENT_CHILDHOODTRUAMAS;
DROP TABLE IF EXISTS MOTORVEHICLEACCIDENT;
DROP TABLE IF EXISTS PATIENT_MOTORVEHICLEACCIDENTS;
DROP TABLE IF EXISTS HOMEACCIDENTS;
DROP TABLE IF EXISTS PATIENT_HOMEACCIDENTS;
DROP TABLE IF EXISTS SPORTSACCIDENTS;
DROP TABLE IF EXISTS PATIENT_SPORTSACCIDENTS;
DROP TABLE IF EXISTS WORKACCIDENTS;
DROP TABLE IF EXISTS PATIENT_WORKACCIDENTS;
DROP TABLE IF EXISTS COMPLAINTS;
DROP TABLE IF EXISTS PATIENT_COMPLAINTS;


CREATE TABLE PATIENTS (
    ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    PATIENT_NUMBER INT(10) NOT NULL,
    TITLE ENUM('MR', 'MRS', 'MISS', 'MS', 'DR'),
    FIRSTNAME VARCHAR(50) NOT NULL,
    LASTNAME VARCHAR(50) NOT NULL,
    DOB DATE,
    ADDRESS VARCHAR(100) NOT NULL,
    HOMEPHONE VARCHAR(50) NOT NULL,
    WORKPHONE VARCHAR(50) NOT NULL,
    CELLPHONE VARCHAR(50) NOT NULL,
    OCCUPATION VARCHAR(50) NOT NULL,
    EMPLOYER VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    HEAR_ABOUT_US VARCHAR(50) NOT NULL,
    EMERGENCYCONTACT VARCHAR(50) NOT NULL,
    EMERGENCYCONTACT_PHONE VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE INDEX PATIENT_NUMBER (PATIENT_NUMBER)
) COLLATE='utf8_general_ci' ENGINE=InnoDB AUTO_INCREMENT=1;

CREATE TABLE CHIROPRACTICEXPERIENCES (
    ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    NAME  VARCHAR(50),
    LOCATION VARCHAR(50),
    PHONE VARCHAR(50),
    LAST_VISIT DATE,
    XRAY_TAKEN TINYINT(1),
    PRIMARY KEY (ID)
) COLLATE='utf8_general_ci' ENGINE=InnoDB AUTO_INCREMENT=1;

CREATE TABLE PATIENT_CHIROPRACTICEXPERIENCES (  
    PATIENT_ID INT(10) UNSIGNED NOT NULL,  
    CHIROPRACTICEXPERIENCE_ID INT(10) UNSIGNED NOT NULL,  
    KEY PATIENT (PATIENT_ID),  
    KEY CHIROPRACTICEXPERIENCE (CHIROPRACTICEXPERIENCE_ID),  
    CONSTRAINT PATIENT FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS (ID) ON DELETE CASCADE ON UPDATE CASCADE,  
    CONSTRAINT CHIROPRACTICEXPERIENCE FOREIGN KEY (CHIROPRACTICEXPERIENCE_ID) REFERENCES CHIROPRACTICEXPERIENCES (ID) ON DELETE CASCADE ON UPDATE CASCADE  
) COLLATE='utf8_general_ci' ENGINE=InnoDB;

CREATE TABLE FAMILYHISTORIES (
    ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    HEART_DISEASE TINYINT(1),
    ARTHRITIS TINYINT(1),
    CANCER TINYINT(1),
    DIABETES TINYINT(1),
    PSYCHOSOCIAL_DISEASE TINYINT(1),
    OTHER TINYINT(1),
    OTHER_DESCRIPTION VARCHAR(100),
    PRIMARY KEY(ID)
) COLLATE='utf8_general_ci' ENGINE=InnoDB AUTO_INCREMENT=1;

CREATE TABLE PATIENT_FAMILYHISTORIES (
    PATIENT_ID INT(10) UNSIGNED NOT NULL,
    FAMILYHISTORY_ID INT(10) UNSIGNED NOT NULL,
    KEY PATIENT (PATIENT_ID),  
    KEY FAMILYHISTORY (FAMILYHISTORY_ID),
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (FAMILYHISTORY_ID) REFERENCES FAMILYHISTORIES (ID) ON DELETE CASCADE ON UPDATE CASCADE
) COLLATE='utf8_general_ci' ENGINE=InnoDB;

CREATE TABLE MEDICALHISTORIES (
    ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    FAMILY_DOCTOR_NAME VARCHAR(50),
    FAMILY_DOCTOR_PHONE VARCHAR(50),
    FAMILY_DOCTOR_ADDRESS VARCHAR(50),
    LAST_FULL_CHECKUP DATE,
    ON_MEDICATION TINYINT(1),
    MEDICATION_TYPE1 VARCHAR(50),
    MEDICATION_TYPE1_FOR VARCHAR(50),
    MEDICATION_TYPE1_DOSE VARCHAR(50),
    MEDICATION_TYPE1_FREQUENCY VARCHAR(50),
    MEDICATION_TYPE2 VARCHAR(50),
    MEDICATION_TYPE2_FOR VARCHAR(50),
    MEDICATION_TYPE2_DOSE VARCHAR(50),
    MEDICATION_TYPE2_FREQUENCY VARCHAR(50),
    SURGERY1 VARCHAR(50),
    SURGERY1_DATE DATE,
    SURGERY1_COMPLICATIONS TINYINT(1),
    SURGERY2 VARCHAR(50),
    SURGERY2_DATE DATE,
    SURGERY2_COMPLICATIONS TINYINT(1),
    VISION TINYINT(1),
    HEARING TINYINT(1),
    SMELL TINYINT(1),
    TASTE TINYINT(1),
    DIZZINESS TINYINT(1),
    HEADACHES TINYINT(1),
    DIFFICULTY_SWALLOWING TINYINT(1),
    LOSS_OF_BALANCE TINYINT(1),
    NIGHT_SWEATS TINYINT(1),
    DIABETES TINYINT(1),
    STROKE TINYINT(1),
    ANEURYSM TINYINT(1),
    HEART_CONDITION TINYINT(1),
    OSTEOPROSIS TINYINT(1),
    ARTHRITIS TINYINT(1),
    PROSTATE_DISORDER TINYINT(1),
    MENSTRUAL_PROBLEMS TINYINT(1),
    HEPATITIS TINYINT(1),
    HIV_INFECTED TINYINT(1),
    SHORTNESS_OF_BREATH TINYINT(1),
    CANCER TINYINT(1),
    STD TINYINT(1),
    TUBERCULOSIS TINYINT(1),
    CHEST_PAIN TINYINT(1),
    HIGH_BLOOD_PRESSURE TINYINT(1),
    DIGESTIVE_PROBLEMS TINYINT(1),
    BOWL_PROBLEMS TINYINT(1),
    BLADDER_PROBLEMS TINYINT(1),
    SIGNIFICANT_WEIGHT_LOSS TINYINT(1),
    PINS_AND_NEEDLES_IN_ARM TINYINT(1),
    WEAKNESS_IN_FINGERS TINYINT(1),
    NUMBNESS_IN_FINGERS TINYINT(1),
    WEAKNESS_IN_LEGS TINYINT(1),
    NUMBNESS_IN_LEGS TINYINT(1),
    BACK_PAIN TINYINT(1),
    NECK_PAIN TINYINT(1),
    TMJ_DISORDER TINYINT(1),
    EAR_RINGING TINYINT(1),
    OTHER TINYINT(1),
    OTHER_DESCRIPTION VARCHAR(100),
    PREGNANCY ENUM('YES', 'NO', 'MAYBE'),
    LAST_MENSTRUAL_CYCLE DATE,
    ALLOWED_TO_CONTACT_MEDICALDOCTOR TINYINT(1),
    PRIMARY KEY(ID)
) COLLATE='utf8_general_ci' ENGINE=InnoDB AUTO_INCREMENT=1;

CREATE TABLE PATIENT_MEDICALHISTORIES (
    PATIENT_ID INT(10) UNSIGNED NOT NULL,
    MEDICALHISTORY_ID INT(10) UNSIGNED NOT NULL,
    KEY PATIENT (PATIENT_ID),  
    KEY MEDICALHISTORY (MEDICALHISTORY_ID),
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (MEDICALHISTORY_ID) REFERENCES MEDICALHISTORIES (ID) ON DELETE CASCADE ON UPDATE CASCADE
) COLLATE='utf8_general_ci' ENGINE=InnoDB;

CREATE TABLE HEALTHHABITS (
    ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    SMOKER TINYINT(1),
	SMOKE_QUANTITY VARCHAR(50),
    DID_DO_DRINK TINYINT(1),
    AMOUNT_OF_DRINKS VARCHAR(100),
    AMOUNT_OF_WATER VARCHAR(100),
    SPORTS_EXERCISE_ACTIVITY VARCHAR(100),
    EXERCISE_REGULARLY TINYINT(1),
    EXERCISE_FREQUENCY VARCHAR(100),
    SLEEP_POSITION ENUM ('BACK', 'SIDE', 'STOMACH'),
    NUMBER_OF_PILLOWS VARCHAR(50),
    DID_DO_WEAR_ORTHODICS TINYINT(1),
    NON_MEDICAL_CARE TINYINT(1),
    NON_MEDICAL_CARE_DESCRIPTION VARCHAR(100),
    PRIMARY KEY(ID)
) COLLATE='utf8_general_ci' ENGINE=InnoDB AUTO_INCREMENT=1;

CREATE TABLE PATIENT_HEALTHHABITS (
    PATIENT_ID INT(10) UNSIGNED NOT NULL,
    HEALTHHABIT_ID INT(10) UNSIGNED NOT NULL,
    KEY PATIENT (PATIENT_ID),  
    KEY HEALTHHABIT (HEALTHHABIT_ID),
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (HEALTHHABIT_ID) REFERENCES HEALTHHABITS (ID) ON DELETE CASCADE ON UPDATE CASCADE
) COLLATE='utf8_general_ci' ENGINE=InnoDB;

CREATE TABLE CHILDHOODTRUAMAS (
    ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    CHILDHOODTRUAMA TINYINT(1),
	TRUAMA_DATE DATE,
	BODYPARTS_INJURED VARCHAR(50),
	INJURIES_RESOLVED TINYINT(1),
	BRIEF_ACCOUNT VARCHAR(100),
	MEDICAL_CARE_RECEIVED TINYINT(1),
	CARE_GIVEN_BY_DOCTOR VARCHAR(50),
	CARE_TYPE_GIVEN VARCHAR(100),
    PRIMARY KEY(ID)
) COLLATE='utf8_general_ci' ENGINE=InnoDB AUTO_INCREMENT=1;

CREATE TABLE PATIENT_CHILDHOODTRUAMAS (
    PATIENT_ID INT(10) UNSIGNED NOT NULL,
    CHILDHOODTRUAMA_ID INT(10) UNSIGNED NOT NULL,
    KEY PATIENT (PATIENT_ID),  
    KEY  (CHILDHOODTRUAMA_ID),
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (CHILDHOODTRUAMA_ID) REFERENCES CHILDHOODTRUAMAS (ID) ON DELETE CASCADE ON UPDATE CASCADE
) COLLATE='utf8_general_ci' ENGINE=InnoDB;

CREATE TABLE MOTORVEHICLEACCIDENTS (
    ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    MOTORVEHICLE_ACCIDENT TINYINT(1),
	ACCIDENT_DATE DATE,
	DRIVER_PASSENGER ENUM('DRIVER','PASSENGER'),
	WEARING_SEATBELT TINYINT(1),
	VEHICLE_COLLISION ENUM('SIDE', 'FRONT', 'REAR'),
	STRIKE_HEAD TINYINT(1),
	LOSSCONCIOUSNESS TINYINT(1),
	SENT_TO_HOSPITAL TINYINT(1),
	XRAY_TAKEN TINYINT(1),
	MEDICATION_GIVEN TINYINT(1),
	CARE_TYPE_GIVEN VARCHAR(100),
	CARE_GIVEN_BY_DOCTOR VARCHAR(50),
	INJURIES_SUSTAINED VARCHAR(100),
	INJURIES_RESOLVED TINYINT(1),
    PRIMARY KEY(ID)
) COLLATE='utf8_general_ci' ENGINE=InnoDB AUTO_INCREMENT=1;

CREATE TABLE PATIENT_MOTORVEHICLEACCIDENTS (
    PATIENT_ID INT(10) UNSIGNED NOT NULL,
    MOTORVEHICLEACCIDENT_ID INT(10) UNSIGNED NOT NULL,
    KEY PATIENT (PATIENT_ID),  
    KEY MOTORVEHICLEACCIDENT (MOTORVEHICLEACCIDENT_ID),
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (MOTORVEHICLEACCIDENT_ID) REFERENCES MOTORVEHICLEACCIDENTS (ID) ON DELETE CASCADE ON UPDATE CASCADE
) COLLATE='utf8_general_ci' ENGINE=InnoDB;

CREATE TABLE HOMEACCIDENTS (
    ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    HOME_ACCIDENT TINYINT(1),
	ACCIDENT_DATE DATE,
	BODYPARTS_INJURED VARCHAR(50),
	INJURIES_RESOLVED TINYINT(1),
	BRIEF_ACCOUNT VARCHAR(100),
	MEDICAL_CARE_RECEIVED TINYINT(1),
	CARE_GIVEN_BY_DOCTOR VARCHAR(50),
	CARE_TYPE_GIVEN VARCHAR(100),
    PRIMARY KEY(ID)
) COLLATE='utf8_general_ci' ENGINE=InnoDB AUTO_INCREMENT=1;

CREATE TABLE PATIENT_HOMEACCIDENTS (
    PATIENT_ID INT(10) UNSIGNED NOT NULL,
    HOMEACCIDENT_ID INT(10) UNSIGNED NOT NULL,
    KEY PATIENT (PATIENT_ID),  
    KEY HOMEACCIDENT (HOMEACCIDENT_ID),
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (HOMEACCIDENT_ID) REFERENCES HOMEACCIDENTS (ID) ON DELETE CASCADE ON UPDATE CASCADE
) COLLATE='utf8_general_ci' ENGINE=InnoDB;

CREATE TABLE SPORTSACCIDENTS (
    ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    SPORTS_ACCIDENT TINYINT(1),
	ACCIDENT_DATE DATE,
	BODYPARTS_INJURED VARCHAR(50),
	INJURIES_RESOLVED TINYINT(1),
	BRIEF_ACCOUNT VARCHAR(100),
	MEDICAL_CARE_RECEIVED TINYINT(1),
	CARE_GIVEN_BY_DOCTOR VARCHAR(50),
	CARE_TYPE_GIVEN VARCHAR(100),
    PRIMARY KEY(ID)
) COLLATE='utf8_general_ci' ENGINE=InnoDB AUTO_INCREMENT=1;

CREATE TABLE PATIENT_SPORTSACCIDENTS (
    PATIENT_ID INT(10) UNSIGNED NOT NULL,
    SPORTSACCIDENT_ID INT(10) UNSIGNED NOT NULL,
    KEY PATIENT (PATIENT_ID),  
    KEY SPORTSACCIDENT (SPORTSACCIDENT_ID),
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (SPORTSACCIDENT_ID) REFERENCES SPORTSACCIDENTS (ID) ON DELETE CASCADE ON UPDATE CASCADE
) COLLATE='utf8_general_ci' ENGINE=InnoDB;

CREATE TABLE WORKACCIDENTS (
    ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    WORK_ACCIDENT TINYINT(1),
	ACCIDENT_DATE DATE,
	EMPLOYER VARCHAR(50),
	WSIB_CLAIM TINYINT(1),
	DISABILITY TINYINT(1),
	DISABILITIES VARCHAR(50),
	BODYPARTS_INJURED VARCHAR(50),
	XRAY_TAKEN TINYINT(1),
	INJURIES_SUSTAINED VARCHAR(50),
	INJURIES_RESOLVED TINYINT(1),
	BRIEF_ACCOUNT VARCHAR(100),
	MEDICAL_CARE_RECEIVED TINYINT(1),
	CARE_GIVEN_BY_DOCTOR VARCHAR(50),
	CARE_TYPE_GIVEN VARCHAR(100),
    PRIMARY KEY(ID)
) COLLATE='utf8_general_ci' ENGINE=InnoDB AUTO_INCREMENT=1;

CREATE TABLE PATIENT_WORKACCIDENTS (
    PATIENT_ID INT(10) UNSIGNED NOT NULL,
    WORKACCIDENT_ID INT(10) UNSIGNED NOT NULL,
    KEY PATIENT (PATIENT_ID),  
    KEY WORKACCIDENT (WORKACCIDENT_ID),
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (WORKACCIDENT_ID) REFERENCES WORKACCIDENTS (ID) ON DELETE CASCADE ON UPDATE CASCADE
) COLLATE='utf8_general_ci' ENGINE=InnoDB;

CREATE TABLE COMPLAINTS (
    ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    SHARP TINYINT(1),
    DULL TINYINT(1),
    THROBBING TINYINT(1),
    ACHING TINYINT(1),
    BURNING TINYINT(1),
    STABBING TINYINT(1),
    WEAKNESS TINYINT(1),
    NUMBNESS TINYINT(1),
    TINGLING TINYINT(1),
    OTHER TINYINT(1),
    OTHER_DESCRIPTION VARCHAR(100),
    LOCATION VARCHAR(100),
    COMPLAINT_DATE DATE,
    START_DATE DATE,
    PREVIOUS_OCCURANCE TINYINT(1),
    PREVIOUS_OCCURANCE_DATE DATE,
    HOW_IT_HAPPENED VARCHAR(100),
    WHAT_MAKES_WORST VARCHAR(100),
    WHAT_MAKES_BETTER VARCHAR(100),
    PAIN_RADIATES VARCHAR(100),
    PAIN_RADIATES_WHERE VARCHAR(100),
    PAIN_PATTERN ENUM('CONSTANT', 'INTERMITTENT', 'VARIES', 'NOPATTERN'),
    PAIN_SCALE ENUM('ONE', 'TWO', 'THREE', 'FOUR', 'FIVE', 'SIX', 'SEVEN', 'EIGHT', 'NINE', 'TEN'),
    PAIN_WORST ENUM('MORNING', 'MIDAFTERNOON', 'EVENING', 'ATNIGHT'),
    PRIMARY KEY(ID)
) COLLATE='utf8_general_ci' ENGINE=InnoDB AUTO_INCREMENT=1;

CREATE TABLE PATIENT_COMPLAINTS (
    PATIENT_ID INT(10) UNSIGNED NOT NULL,
    COMPLAINT_ID INT(10) UNSIGNED NOT NULL,
    KEY PATIENT (PATIENT_ID),  
    KEY COMPLAINT (COMPLAINT_ID),
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (COMPLAINT_ID) REFERENCES COMPLAINTS (ID) ON DELETE CASCADE ON UPDATE CASCADE
) COLLATE='utf8_general_ci' ENGINE=InnoDB;
